---
- hosts: all
  become: yes
  environment:
    #DEBIAN_FRONTEND: noninteractive
    GIT_SSL_NO_VERIFY: 1
    LANGUAGE: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  roles:
  - base
  - ldap
  - ruby
  - go
  - postgresql
  - redis
  - gitlab
